apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: aiops-pod-delete
  namespace: aiops
spec:
  appinfo:
    appns: aiops
    applabel: "app=aiops-agent"
    appkind: "deployment"
  chaosServiceAccount: chaos-service-account
  experiments:
  - name: pod-delete
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: "30"
        - name: CHAOS_INTERVAL
          value: "10"
        - name: FORCE
          value: "false"
